from __future__ import annotations

import json
import platform
import re
import shutil
import subprocess
import time
from pathlib import Path
from typing import Callable

from app.config import settings
from app.schemas import MLXVlmAudioStatus
from app.services.chunked_audio import ChunkTranscriptionConfig, transcribe_audio_in_chunks
from app.services.audio_engine import AudioEngineResult
from app.services.exporters import segment_text
from app.services.media import ffmpeg_executable
from app.services.media import OperationCanceled
from app.services.qwen_audio.audio_preprocess import audio_duration_seconds


def is_macos() -> bool:
    return platform.system().lower() == "darwin"


def is_apple_silicon() -> bool:
    return platform.machine().lower() in {"arm64", "aarch64"}


def ffmpeg_available() -> bool:
    executable = ffmpeg_executable()
    return bool(Path(executable).exists() or shutil.which(executable) or shutil.which("ffmpeg"))


def python_available(python_executable: str | None = None) -> bool:
    executable = (python_executable or settings.mlx_vlm_python).strip()
    return bool(executable and (Path(executable).exists() or shutil.which(executable)))


def configured_model(value: str | None = None) -> str:
    return (value or "").strip()


def is_local_model_path(value: str) -> bool:
    return bool(value and Path(value).expanduser().exists())


def local_model_type(model_path_or_repo: str) -> str | None:
    if not is_local_model_path(model_path_or_repo):
        return None
    config_path = Path(model_path_or_repo).expanduser() / "config.json"
    if not config_path.exists():
        return None
    try:
        payload = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    model_type = payload.get("model_type")
    return str(model_type).strip().lower() if model_type else None


def is_mlx_vlm_audio_model(model_path_or_repo: str | None) -> bool:
    configured = configured_model(model_path_or_repo)
    if not configured:
        return False
    model_type = local_model_type(configured)
    if model_type:
        return model_type == "gemma4"
    text = configured.lower()
    return "gemma4" in text or "mlx-vlm" in text or "mlx_vlm" in text


def dependency_available(python_executable: str | None = None) -> bool:
    executable = (python_executable or settings.mlx_vlm_python).strip()
    if not python_available(executable):
        return False
    try:
        result = subprocess.run(
            [executable, "-c", "import importlib.util; raise SystemExit(0 if importlib.util.find_spec('mlx_vlm') else 1)"],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return result.returncode == 0


def mlx_vlm_audio_status(model_path_or_repo: str | None = None) -> MLXVlmAudioStatus:
    configured = configured_model(model_path_or_repo)
    platform_supported = is_macos() and is_apple_silicon()
    py_available = python_available()
    dependency_installed = dependency_available() if py_available else False
    model_configured = bool(configured)
    model_type = local_model_type(configured) if configured else None
    ffmpeg_ok = ffmpeg_available()
    available = platform_supported and py_available and dependency_installed and model_configured and ffmpeg_ok

    reason = None
    hint = None
    if not platform_supported:
        reason = "当前平台不是 macOS Apple Silicon。"
        hint = "Gemma4 MLX 音频模型主要适用于 M 系列 Mac。"
    elif not py_available:
        reason = "未找到 mlx_vlm Python 解释器。"
        hint = "请先运行项目安装脚本创建 .venv；如需自定义解释器，可设置 AUDIO_TRANSCRIBE_MLX_VLM_PYTHON。"
    elif not dependency_installed:
        reason = "该 Python 环境未检测到 mlx_vlm。"
        hint = "请运行项目安装脚本安装 requirements.txt，或在当前 .venv 中安装 mlx-vlm。"
    elif not model_configured:
        reason = "未配置 Gemma4 MLX 音频模型路径。"
        hint = "请选择或填写本地 gemma4-e4b-qat-4bit 模型目录。"
    elif not ffmpeg_ok:
        reason = "FFmpeg 不可用。"
        hint = "安装 FFmpeg，或设置 AUDIO_TRANSCRIBE_FFMPEG 指向可执行文件。"
    elif is_local_model_path(configured) and model_type not in {"gemma4", None}:
        reason = f"当前 mlx-vlm 音频入口未确认支持 {model_type} 模型。"
        hint = "请选择 Gemma4 MLX Audio/Text 模型，Qwen2-Audio 请继续使用 MLX Audio 管线。"
        available = False
    elif not is_local_model_path(configured):
        reason = "配置的 Gemma4 MLX 模型路径不存在。"
        hint = "请填写已下载的本地模型目录。"
        available = False

    return MLXVlmAudioStatus(
        available=available,
        platform_supported=platform_supported,
        dependency_installed=dependency_installed,
        model_configured=model_configured,
        python_available=py_available,
        ffmpeg_available=ffmpeg_ok,
        is_macos=is_macos(),
        is_apple_silicon=is_apple_silicon(),
        os=platform.system() or "unknown",
        arch=platform.machine() or "unknown",
        python_executable=settings.mlx_vlm_python,
        model_path_or_repo=configured,
        model_type=model_type,
        max_tokens=settings.mlx_vlm_max_tokens,
        reason=reason,
        hint=hint,
    )


def parse_mlx_vlm_generate_output(stdout: str) -> str:
    parts = stdout.split("==========")
    if len(parts) >= 3:
        body = parts[1]
        marker = "<|turn>model"
        if marker in body:
            body = body.split(marker, 1)[1]
        return body.strip()

    lines = []
    for raw_line in stdout.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith(("Files:", "Prompt:", "Generation:", "Peak memory:")):
            continue
        lines.append(line)
    return "\n".join(lines).strip()


_TRADITIONAL_TO_SIMPLIFIED = str.maketrans(
    {
        "萬": "万",
        "與": "与",
        "專": "专",
        "業": "业",
        "東": "东",
        "絲": "丝",
        "丟": "丢",
        "兩": "两",
        "嚴": "严",
        "喪": "丧",
        "個": "个",
        "豐": "丰",
        "臨": "临",
        "為": "为",
        "麗": "丽",
        "舉": "举",
        "麼": "么",
        "義": "义",
        "烏": "乌",
        "樂": "乐",
        "喬": "乔",
        "習": "习",
        "鄉": "乡",
        "書": "书",
        "買": "买",
        "亂": "乱",
        "爭": "争",
        "於": "于",
        "虧": "亏",
        "雲": "云",
        "亞": "亚",
        "產": "产",
        "畝": "亩",
        "親": "亲",
        "褻": "亵",
        "億": "亿",
        "僅": "仅",
        "從": "从",
        "倉": "仓",
        "儀": "仪",
        "們": "们",
        "價": "价",
        "眾": "众",
        "優": "优",
        "會": "会",
        "傘": "伞",
        "偉": "伟",
        "傳": "传",
        "傷": "伤",
        "倫": "伦",
        "偽": "伪",
        "體": "体",
        "餘": "余",
        "佛": "佛",
        "傭": "佣",
        "債": "债",
        "傾": "倾",
        "僑": "侨",
        "儂": "侬",
        "儘": "尽",
        "償": "偿",
        "兒": "儿",
        "黨": "党",
        "蘭": "兰",
        "關": "关",
        "興": "兴",
        "養": "养",
        "獸": "兽",
        "內": "内",
        "岡": "冈",
        "冊": "册",
        "寫": "写",
        "軍": "军",
        "農": "农",
        "沖": "冲",
        "決": "决",
        "況": "况",
        "凍": "冻",
        "淨": "净",
        "涼": "凉",
        "減": "减",
        "湊": "凑",
        "凜": "凛",
        "幾": "几",
        "鳳": "凤",
        "憑": "凭",
        "凱": "凯",
        "擊": "击",
        "鑿": "凿",
        "剎": "刹",
        "劑": "剂",
        "剛": "刚",
        "創": "创",
        "刪": "删",
        "別": "别",
        "剮": "剐",
        "劍": "剑",
        "劇": "剧",
        "劉": "刘",
        "劊": "刽",
        "劑": "剂",
        "勁": "劲",
        "動": "动",
        "務": "务",
        "勛": "勋",
        "勝": "胜",
        "勞": "劳",
        "勢": "势",
        "勻": "匀",
        "匯": "汇",
        "區": "区",
        "醫": "医",
        "華": "华",
        "協": "协",
        "單": "单",
        "賣": "卖",
        "盧": "卢",
        "衛": "卫",
        "卻": "却",
        "廠": "厂",
        "廳": "厅",
        "歷": "历",
        "厲": "厉",
        "壓": "压",
        "厭": "厌",
        "廁": "厕",
        "廈": "厦",
        "縣": "县",
        "參": "参",
        "雙": "双",
        "發": "发",
        "變": "变",
        "敘": "叙",
        "疊": "叠",
        "葉": "叶",
        "號": "号",
        "嘆": "叹",
        "嘰": "叽",
        "嚇": "吓",
        "呂": "吕",
        "嗎": "吗",
        "啟": "启",
        "吳": "吴",
        "吶": "呐",
        "員": "员",
        "聽": "听",
        "啞": "哑",
        "啟": "启",
        "問": "问",
        "啣": "衔",
        "國": "国",
        "圖": "图",
        "圓": "圆",
        "聖": "圣",
        "場": "场",
        "壞": "坏",
        "塊": "块",
        "堅": "坚",
        "壇": "坛",
        "壩": "坝",
        "墳": "坟",
        "墜": "坠",
        "墾": "垦",
        "壘": "垒",
        "壟": "垄",
        "壯": "壮",
        "聲": "声",
        "殼": "壳",
        "壺": "壶",
        "處": "处",
        "備": "备",
        "複": "复",
        "夠": "够",
        "頭": "头",
        "誇": "夸",
        "夾": "夹",
        "奪": "夺",
        "奮": "奋",
        "獎": "奖",
        "奧": "奥",
        "婦": "妇",
        "媽": "妈",
        "妝": "妆",
        "姍": "姗",
        "娛": "娱",
        "婁": "娄",
        "婦": "妇",
        "嬰": "婴",
        "學": "学",
        "寧": "宁",
        "寶": "宝",
        "實": "实",
        "寵": "宠",
        "審": "审",
        "憲": "宪",
        "宮": "宫",
        "寬": "宽",
        "賓": "宾",
        "寢": "寝",
        "對": "对",
        "尋": "寻",
        "導": "导",
        "壽": "寿",
        "將": "将",
        "爾": "尔",
        "塵": "尘",
        "嘗": "尝",
        "堯": "尧",
        "尷": "尴",
        "屍": "尸",
        "盡": "尽",
        "層": "层",
        "屜": "屉",
        "屬": "属",
        "歲": "岁",
        "島": "岛",
        "嶺": "岭",
        "峽": "峡",
        "巋": "岿",
        "崑": "昆",
        "崗": "岗",
        "嶄": "崭",
        "嶇": "岖",
        "嵐": "岚",
        "巖": "岩",
        "巔": "巅",
        "鞏": "巩",
        "幣": "币",
        "帥": "帅",
        "師": "师",
        "帳": "帐",
        "帶": "带",
        "幀": "帧",
        "幫": "帮",
        "幹": "干",
        "庫": "库",
        "應": "应",
        "廟": "庙",
        "龐": "庞",
        "廢": "废",
        "廣": "广",
        "莊": "庄",
        "慶": "庆",
        "廬": "庐",
        "開": "开",
        "異": "异",
        "棄": "弃",
        "張": "张",
        "彌": "弥",
        "彎": "弯",
        "彈": "弹",
        "強": "强",
        "歸": "归",
        "當": "当",
        "錄": "录",
        "彥": "彦",
        "徹": "彻",
        "徑": "径",
        "徠": "徕",
        "憶": "忆",
        "懺": "忏",
        "憂": "忧",
        "懷": "怀",
        "態": "态",
        "慫": "怂",
        "憐": "怜",
        "總": "总",
        "戀": "恋",
        "恆": "恒",
        "懇": "恳",
        "惡": "恶",
        "慟": "恸",
        "惱": "恼",
        "悅": "悦",
        "懸": "悬",
        "慳": "悭",
        "驚": "惊",
        "懼": "惧",
        "慘": "惨",
        "懲": "惩",
        "憊": "惫",
        "慚": "惭",
        "慣": "惯",
        "慪": "怄",
        "憤": "愤",
        "願": "愿",
        "戲": "戏",
        "戰": "战",
        "戶": "户",
        "撲": "扑",
        "執": "执",
        "擴": "扩",
        "掃": "扫",
        "揚": "扬",
        "擾": "扰",
        "撫": "抚",
        "拋": "抛",
        "摶": "抟",
        "摳": "抠",
        "掄": "抡",
        "搶": "抢",
        "護": "护",
        "報": "报",
        "擔": "担",
        "擬": "拟",
        "攏": "拢",
        "揀": "拣",
        "擁": "拥",
        "攔": "拦",
        "擰": "拧",
        "撥": "拨",
        "擇": "择",
        "掛": "挂",
        "摯": "挚",
        "摟": "搂",
        "撓": "挠",
        "擋": "挡",
        "撟": "挢",
        "掙": "挣",
        "擠": "挤",
        "揮": "挥",
        "撏": "挦",
        "輓": "挽",
        "挾": "挟",
        "捨": "舍",
        "撈": "捞",
        "損": "损",
        "撿": "捡",
        "換": "换",
        "搗": "捣",
        "據": "据",
        "捲": "卷",
        "掃": "扫",
        "掄": "抡",
        "摑": "掴",
        "擲": "掷",
        "摻": "掺",
        "摜": "掼",
        "攬": "揽",
        "攙": "搀",
        "擱": "搁",
        "摟": "搂",
        "攪": "搅",
        "攜": "携",
        "攝": "摄",
        "攤": "摊",
        "攣": "挛",
        "攢": "攒",
        "敵": "敌",
        "斂": "敛",
        "數": "数",
        "齋": "斋",
        "斕": "斓",
        "斬": "斩",
        "斷": "断",
        "無": "无",
        "舊": "旧",
        "時": "时",
        "曠": "旷",
        "曇": "昙",
        "晝": "昼",
        "顯": "显",
        "晉": "晋",
        "曬": "晒",
        "曉": "晓",
        "暈": "晕",
        "暢": "畅",
        "暫": "暂",
        "曄": "晔",
        "術": "术",
        "樸": "朴",
        "機": "机",
        "殺": "杀",
        "雜": "杂",
        "權": "权",
        "條": "条",
        "來": "来",
        "楊": "杨",
        "傑": "杰",
        "鬆": "松",
        "板": "板",
        "極": "极",
        "構": "构",
        "樅": "枞",
        "樞": "枢",
        "棗": "枣",
        "槍": "枪",
        "楓": "枫",
        "梟": "枭",
        "櫃": "柜",
        "檸": "柠",
        "檢": "检",
        "棧": "栈",
        "棟": "栋",
        "欄": "栏",
        "樹": "树",
        "棲": "栖",
        "樣": "样",
        "欒": "栾",
        "棄": "弃",
        "榮": "荣",
        "樁": "桩",
        "橋": "桥",
        "樺": "桦",
        "檜": "桧",
        "槳": "桨",
        "夢": "梦",
        "檔": "档",
        "檢": "检",
        "檳": "槟",
        "櫻": "樱",
        "歡": "欢",
        "歐": "欧",
        "殲": "歼",
        "殘": "残",
        "毆": "殴",
        "毀": "毁",
        "氣": "气",
        "氫": "氢",
        "氬": "氩",
        "湯": "汤",
        "溝": "沟",
        "沒": "没",
        "灃": "沣",
        "漚": "沤",
        "瀝": "沥",
        "淪": "沦",
        "滄": "沧",
        "滬": "沪",
        "淚": "泪",
        "瀉": "泻",
        "潑": "泼",
        "澤": "泽",
        "潔": "洁",
        "灑": "洒",
        "窪": "洼",
        "浹": "浃",
        "淺": "浅",
        "漿": "浆",
        "澆": "浇",
        "濁": "浊",
        "測": "测",
        "濟": "济",
        "瀏": "浏",
        "渾": "浑",
        "濃": "浓",
        "濤": "涛",
        "澗": "涧",
        "漲": "涨",
        "澀": "涩",
        "淵": "渊",
        "漁": "渔",
        "瀋": "沈",
        "滲": "渗",
        "溫": "温",
        "灣": "湾",
        "濕": "湿",
        "潰": "溃",
        "濺": "溅",
        "滾": "滚",
        "滿": "满",
        "濾": "滤",
        "濫": "滥",
        "灤": "滦",
        "濱": "滨",
        "灘": "滩",
        "災": "灾",
        "燦": "灿",
        "爐": "炉",
        "點": "点",
        "煉": "炼",
        "熾": "炽",
        "爍": "烁",
        "爛": "烂",
        "爭": "争",
        "爺": "爷",
        "爾": "尔",
        "牆": "墙",
        "牽": "牵",
        "犧": "牺",
        "狀": "状",
        "猶": "犹",
        "狽": "狈",
        "獄": "狱",
        "獨": "独",
        "獲": "获",
        "獵": "猎",
        "獸": "兽",
        "獻": "献",
        "現": "现",
        "璽": "玺",
        "琺": "珐",
        "電": "电",
        "畫": "画",
        "暢": "畅",
        "疇": "畴",
        "瘋": "疯",
        "瘍": "疡",
        "瘡": "疮",
        "瘧": "疟",
        "療": "疗",
        "癆": "痨",
        "癇": "痫",
        "癢": "痒",
        "癱": "瘫",
        "癮": "瘾",
        "癬": "癣",
        "皺": "皱",
        "盞": "盏",
        "鹽": "盐",
        "監": "监",
        "蓋": "盖",
        "盜": "盗",
        "盤": "盘",
        "眥": "眦",
        "著": "着",
        "睜": "睁",
        "瞞": "瞒",
        "矚": "瞩",
        "矯": "矫",
        "礦": "矿",
        "碼": "码",
        "磚": "砖",
        "確": "确",
        "磯": "矶",
        "禮": "礼",
        "禍": "祸",
        "禎": "祯",
        "離": "离",
        "禿": "秃",
        "稈": "秆",
        "種": "种",
        "積": "积",
        "稱": "称",
        "穀": "谷",
        "穌": "稣",
        "穩": "稳",
        "窩": "窝",
        "窮": "穷",
        "竄": "窜",
        "竅": "窍",
        "竇": "窦",
        "競": "竞",
        "筆": "笔",
        "筍": "笋",
        "箋": "笺",
        "籠": "笼",
        "築": "筑",
        "篩": "筛",
        "簽": "签",
        "簡": "简",
        "籃": "篮",
        "籌": "筹",
        "籤": "签",
        "類": "类",
        "糞": "粪",
        "糧": "粮",
        "緊": "紧",
        "糾": "纠",
        "紀": "纪",
        "約": "约",
        "紅": "红",
        "紡": "纺",
        "紐": "纽",
        "純": "纯",
        "紗": "纱",
        "綱": "纲",
        "納": "纳",
        "縱": "纵",
        "紛": "纷",
        "紙": "纸",
        "紋": "纹",
        "紡": "纺",
        "紐": "纽",
        "線": "线",
        "練": "练",
        "組": "组",
        "紳": "绅",
        "細": "细",
        "織": "织",
        "終": "终",
        "絆": "绊",
        "絞": "绞",
        "絡": "络",
        "絕": "绝",
        "絨": "绒",
        "統": "统",
        "絲": "丝",
        "綁": "绑",
        "絢": "绚",
        "給": "给",
        "絨": "绒",
        "絳": "绛",
        "絹": "绢",
        "綠": "绿",
        "綢": "绸",
        "維": "维",
        "綿": "绵",
        "綱": "纲",
        "綻": "绽",
        "綜": "综",
        "綽": "绰",
        "綾": "绫",
        "綴": "缀",
        "緩": "缓",
        "締": "缔",
        "編": "编",
        "緣": "缘",
        "縛": "缚",
        "縫": "缝",
        "縣": "县",
        "縴": "纤",
        "縹": "缥",
        "總": "总",
        "績": "绩",
        "繁": "繁",
        "繃": "绷",
        "繳": "缴",
        "繼": "继",
        "纏": "缠",
        "纖": "纤",
        "纜": "缆",
        "罐": "罐",
        "網": "网",
        "羅": "罗",
        "罰": "罚",
        "罷": "罢",
        "聳": "耸",
        "恥": "耻",
        "聶": "聂",
        "職": "职",
        "聯": "联",
        "聰": "聪",
        "聲": "声",
        "聳": "耸",
        "腫": "肿",
        "脅": "胁",
        "膽": "胆",
        "勝": "胜",
        "膠": "胶",
        "膚": "肤",
        "臉": "脸",
        "臘": "腊",
        "臟": "脏",
        "臺": "台",
        "與": "与",
        "興": "兴",
        "舉": "举",
        "艱": "艰",
        "艷": "艳",
        "藝": "艺",
        "節": "节",
        "蕪": "芜",
        "蘆": "芦",
        "蘇": "苏",
        "蘋": "苹",
        "範": "范",
        "莖": "茎",
        "莢": "荚",
        "薦": "荐",
        "蕩": "荡",
        "榮": "荣",
        "葷": "荤",
        "萊": "莱",
        "蓮": "莲",
        "獲": "获",
        "瑩": "莹",
        "鶯": "莺",
        "萬": "万",
        "蔣": "蒋",
        "蒼": "苍",
        "蓋": "盖",
        "蔥": "葱",
        "藍": "蓝",
        "薊": "蓟",
        "薔": "蔷",
        "薑": "姜",
        "薩": "萨",
        "蘊": "蕴",
        "虛": "虚",
        "蟲": "虫",
        "蝕": "蚀",
        "螞": "蚂",
        "蠶": "蚕",
        "蠻": "蛮",
        "術": "术",
        "衝": "冲",
        "袞": "衮",
        "襖": "袄",
        "裝": "装",
        "裡": "里",
        "製": "制",
        "褲": "裤",
        "襲": "袭",
        "見": "见",
        "觀": "观",
        "規": "规",
        "覓": "觅",
        "視": "视",
        "覺": "觉",
        "覽": "览",
        "觸": "触",
        "訂": "订",
        "計": "计",
        "訊": "讯",
        "討": "讨",
        "訓": "训",
        "託": "托",
        "記": "记",
        "訛": "讹",
        "訟": "讼",
        "訣": "诀",
        "訪": "访",
        "設": "设",
        "許": "许",
        "訴": "诉",
        "診": "诊",
        "註": "注",
        "詐": "诈",
        "詔": "诏",
        "評": "评",
        "詞": "词",
        "詠": "咏",
        "該": "该",
        "詳": "详",
        "試": "试",
        "詩": "诗",
        "誠": "诚",
        "話": "话",
        "誕": "诞",
        "誨": "诲",
        "誘": "诱",
        "語": "语",
        "誤": "误",
        "說": "说",
        "課": "课",
        "誰": "谁",
        "調": "调",
        "諒": "谅",
        "談": "谈",
        "請": "请",
        "諸": "诸",
        "諾": "诺",
        "讀": "读",
        "諷": "讽",
        "課": "课",
        "諮": "咨",
        "謀": "谋",
        "謂": "谓",
        "謎": "谜",
        "謗": "谤",
        "謙": "谦",
        "講": "讲",
        "謝": "谢",
        "謠": "谣",
        "謹": "谨",
        "證": "证",
        "譏": "讥",
        "識": "识",
        "譜": "谱",
        "譯": "译",
        "議": "议",
        "譴": "谴",
        "護": "护",
        "變": "变",
        "讚": "赞",
        "讒": "谗",
        "讓": "让",
        "讖": "谶",
        "豈": "岂",
        "豎": "竖",
        "豐": "丰",
        "豬": "猪",
        "貓": "猫",
        "貝": "贝",
        "貞": "贞",
        "負": "负",
        "財": "财",
        "責": "责",
        "賢": "贤",
        "敗": "败",
        "賬": "账",
        "貨": "货",
        "質": "质",
        "販": "贩",
        "貪": "贪",
        "貧": "贫",
        "貶": "贬",
        "購": "购",
        "貯": "贮",
        "貫": "贯",
        "貳": "贰",
        "貴": "贵",
        "貸": "贷",
        "費": "费",
        "貼": "贴",
        "貽": "贻",
        "貿": "贸",
        "賀": "贺",
        "賁": "贲",
        "賂": "赂",
        "賃": "赁",
        "賄": "贿",
        "資": "资",
        "賈": "贾",
        "賊": "贼",
        "賑": "赈",
        "賒": "赊",
        "賓": "宾",
        "賜": "赐",
        "賞": "赏",
        "賠": "赔",
        "賢": "贤",
        "賣": "卖",
        "賤": "贱",
        "賦": "赋",
        "賬": "账",
        "賭": "赌",
        "賴": "赖",
        "賺": "赚",
        "購": "购",
        "賽": "赛",
        "贊": "赞",
        "贈": "赠",
        "贏": "赢",
        "趙": "赵",
        "趕": "赶",
        "趨": "趋",
        "躍": "跃",
        "踐": "践",
        "蹤": "踪",
        "車": "车",
        "軋": "轧",
        "軌": "轨",
        "軒": "轩",
        "轉": "转",
        "輪": "轮",
        "軟": "软",
        "轟": "轰",
        "軸": "轴",
        "輕": "轻",
        "載": "载",
        "較": "较",
        "輔": "辅",
        "輛": "辆",
        "輩": "辈",
        "輝": "辉",
        "輦": "辇",
        "輻": "辐",
        "輯": "辑",
        "輸": "输",
        "轄": "辖",
        "輾": "辗",
        "轅": "辕",
        "轍": "辙",
        "辭": "辞",
        "辯": "辩",
        "邊": "边",
        "遼": "辽",
        "達": "达",
        "遷": "迁",
        "過": "过",
        "運": "运",
        "還": "还",
        "這": "这",
        "進": "进",
        "遠": "远",
        "違": "违",
        "連": "连",
        "遲": "迟",
        "適": "适",
        "選": "选",
        "遺": "遗",
        "遙": "遥",
        "鄧": "邓",
        "鄭": "郑",
        "鄰": "邻",
        "鬱": "郁",
        "郵": "邮",
        "鄉": "乡",
        "鄒": "邹",
        "鄴": "邺",
        "鄺": "邝",
        "醞": "酝",
        "醬": "酱",
        "釀": "酿",
        "釁": "衅",
        "釋": "释",
        "裡": "里",
        "鑒": "鉴",
        "針": "针",
        "釘": "钉",
        "釣": "钓",
        "鈔": "钞",
        "鐘": "钟",
        "鋼": "钢",
        "鈣": "钙",
        "鈉": "钠",
        "鑰": "钥",
        "欽": "钦",
        "鈞": "钧",
        "鈕": "钮",
        "錢": "钱",
        "鉗": "钳",
        "鑽": "钻",
        "鐵": "铁",
        "鈴": "铃",
        "鉛": "铅",
        "鉤": "钩",
        "銘": "铭",
        "銅": "铜",
        "銑": "铣",
        "銜": "衔",
        "鋁": "铝",
        "銳": "锐",
        "銷": "销",
        "銹": "锈",
        "鋒": "锋",
        "鋅": "锌",
        "鋪": "铺",
        "鋰": "锂",
        "銼": "锉",
        "鋯": "锆",
        "鏈": "链",
        "鎖": "锁",
        "鍋": "锅",
        "錘": "锤",
        "錯": "错",
        "錨": "锚",
        "錫": "锡",
        "鑼": "锣",
        "錦": "锦",
        "鍵": "键",
        "鋸": "锯",
        "錳": "锰",
        "鍾": "钟",
        "鍛": "锻",
        "鍬": "锹",
        "鍛": "锻",
        "鎂": "镁",
        "鏤": "镂",
        "鎮": "镇",
        "鎳": "镍",
        "鎊": "镑",
        "鎬": "镐",
        "鎰": "镒",
        "鎘": "镉",
        "鏡": "镜",
        "鏢": "镖",
        "鏽": "锈",
        "鐐": "镣",
        "鐔": "镡",
        "鐳": "镭",
        "鐵": "铁",
        "鐺": "铛",
        "鑄": "铸",
        "鑑": "鉴",
        "鑒": "鉴",
        "鑲": "镶",
        "長": "长",
        "門": "门",
        "閃": "闪",
        "閉": "闭",
        "開": "开",
        "閏": "闰",
        "閒": "闲",
        "間": "间",
        "悶": "闷",
        "閘": "闸",
        "鬧": "闹",
        "閨": "闺",
        "閩": "闽",
        "聞": "闻",
        "閥": "阀",
        "閣": "阁",
        "閱": "阅",
        "闊": "阔",
        "闆": "板",
        "隊": "队",
        "陽": "阳",
        "陰": "阴",
        "陣": "阵",
        "階": "阶",
        "際": "际",
        "陸": "陆",
        "隴": "陇",
        "陳": "陈",
        "陝": "陕",
        "隕": "陨",
        "險": "险",
        "隨": "随",
        "隱": "隐",
        "隸": "隶",
        "雖": "虽",
        "雙": "双",
        "雛": "雏",
        "雜": "杂",
        "雞": "鸡",
        "離": "离",
        "難": "难",
        "霧": "雾",
        "靈": "灵",
        "靜": "静",
        "靦": "腼",
        "韋": "韦",
        "韌": "韧",
        "韓": "韩",
        "韻": "韵",
        "頁": "页",
        "頂": "顶",
        "頃": "顷",
        "項": "项",
        "順": "顺",
        "須": "须",
        "頊": "顼",
        "頑": "顽",
        "頓": "顿",
        "頒": "颁",
        "預": "预",
        "領": "领",
        "頗": "颇",
        "頸": "颈",
        "頻": "频",
        "顆": "颗",
        "題": "题",
        "額": "额",
        "顏": "颜",
        "顯": "显",
        "願": "愿",
        "顛": "颠",
        "類": "类",
        "顧": "顾",
        "顫": "颤",
        "風": "风",
        "颱": "台",
        "颳": "刮",
        "飄": "飘",
        "飛": "飞",
        "飢": "饥",
        "飯": "饭",
        "飲": "饮",
        "飼": "饲",
        "飽": "饱",
        "飾": "饰",
        "餃": "饺",
        "餅": "饼",
        "養": "养",
        "餌": "饵",
        "餓": "饿",
        "餡": "馅",
        "館": "馆",
        "餾": "馏",
        "餿": "馊",
        "饅": "馒",
        "饒": "饶",
        "饞": "馋",
        "馬": "马",
        "馭": "驭",
        "馱": "驮",
        "馳": "驰",
        "驅": "驱",
        "駁": "驳",
        "駐": "驻",
        "駝": "驼",
        "駕": "驾",
        "罵": "骂",
        "驕": "骄",
        "驗": "验",
        "騎": "骑",
        "騙": "骗",
        "騷": "骚",
        "驟": "骤",
        "驢": "驴",
        "髒": "脏",
        "體": "体",
        "髮": "发",
        "鬚": "须",
        "鬥": "斗",
        "鬧": "闹",
        "魯": "鲁",
        "鮑": "鲍",
        "鮮": "鲜",
        "鯉": "鲤",
        "鯨": "鲸",
        "鯊": "鲨",
        "鱷": "鳄",
        "鳥": "鸟",
        "鳩": "鸠",
        "鳳": "凤",
        "鳴": "鸣",
        "鴨": "鸭",
        "鴻": "鸿",
        "鵝": "鹅",
        "鵬": "鹏",
        "鶴": "鹤",
        "鷹": "鹰",
        "鹵": "卤",
        "鹹": "咸",
        "鹽": "盐",
        "麥": "麦",
        "黃": "黄",
        "點": "点",
        "齊": "齐",
        "齒": "齿",
        "齡": "龄",
        "龍": "龙",
        "龜": "龟",
    }
)


def to_simplified_chinese(text: str) -> str:
    try:
        from opencc import OpenCC

        return OpenCC("t2s").convert(text)
    except Exception:
        return text.translate(_TRADITIONAL_TO_SIMPLIFIED)


def clean_transcript_text(text: str) -> str:
    value = re.sub(r"\s+", " ", text or "").strip()
    value = value.strip(" \n\t`'\"“”‘’「」『』")
    if is_no_speech_placeholder(value):
        return ""
    return to_simplified_chinese(value)


def is_no_speech_placeholder(text: str) -> bool:
    value = re.sub(r"\s+", "", to_simplified_chinese(text or "").strip().lower())
    value = value.strip("。.!！?？,，;；:：'\"“”‘’「」『』()（）[]【】")
    if not value:
        return False
    placeholders = {
        "我没有收到任何音频",
        "我没有收到任何音频这句话",
        "没有收到任何音频",
        "我没有听到任何音频",
        "没有听到任何音频",
        "我没有听到任何说话内容",
        "没有听到任何说话内容",
        "音频中没有说话内容",
        "这段音频没有说话内容",
        "这段音频中没有说话内容",
        "音频中没有可转写内容",
        "这段音频没有可转写内容",
        "这段音频中没有可转写内容",
        "没有可转写的人声",
        "音频为空",
        "静音",
        "nospeech",
        "noaudio",
    }
    if value in placeholders:
        return True
    return bool(
        re.fullmatch(r"(我)?(没有|未)(收到|听到)(任何)?(音频|声音|说话内容|人声)", value)
        or re.fullmatch(r"(这段)?音频(中)?(没有|无)(可转写的?)?(说话内容|人声|语音内容|文本内容)", value)
    )


def _run_mlx_vlm_generate(
    *,
    audio_path: Path,
    model_path_or_repo: str,
    prompt: str,
    python_executable: str,
    is_canceled: Callable[[], bool],
) -> str:
    command = [
        python_executable,
        "-m",
        "mlx_vlm.generate",
        "--model",
        model_path_or_repo,
        "--audio",
        str(audio_path),
        "--prompt",
        prompt,
        "--max-tokens",
        str(settings.mlx_vlm_max_tokens),
    ]
    try:
        process = subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
            errors="ignore",
        )
    except OSError as exc:
        raise RuntimeError(f"无法启动 Gemma4 MLX VLM Audio：{exc}") from exc

    started_at = time.monotonic()
    try:
        while process.poll() is None:
            if time.monotonic() - started_at > settings.mlx_vlm_timeout_seconds:
                process.kill()
                raise RuntimeError(f"Gemma4 MLX VLM Audio 转录超时：超过 {settings.mlx_vlm_timeout_seconds} 秒")
            if is_canceled():
                process.terminate()
                try:
                    process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    process.kill()
                raise OperationCanceled("任务已停止")
            try:
                stdout, stderr = process.communicate(timeout=0.5)
            except subprocess.TimeoutExpired:
                continue
            break
        else:
            stdout, stderr = process.communicate()
    except subprocess.TimeoutExpired as exc:
        process.kill()
        raise RuntimeError(f"Gemma4 MLX VLM Audio 转录超时：{exc}") from exc

    if process.returncode != 0:
        detail = (stderr or stdout or "").strip()
        raise RuntimeError(f"Gemma4 MLX VLM Audio 转录失败：{detail}")
    transcript = clean_transcript_text(parse_mlx_vlm_generate_output(stdout))
    return transcript


def transcribe_with_mlx_vlm_audio(
    audio_path: Path,
    model_path_or_repo: str,
    language: str | None = None,
    work_dir: Path | None = None,
    is_canceled: Callable[[], bool] = lambda: False,
    on_partial: Callable[[AudioEngineResult], None] | None = None,
) -> AudioEngineResult:
    del language
    status = mlx_vlm_audio_status(model_path_or_repo)
    if not status.available:
        raise RuntimeError(status.reason or "Gemma4 MLX VLM Audio 前置条件未满足。")

    active_work_dir = work_dir or audio_path.parent / "mlx_vlm_audio_work"
    base_metadata = {
        "engine": "mlx-vlm-audio",
        "backend": "mlx-vlm",
        "model": model_path_or_repo,
        "python": status.python_executable,
        "prompt": settings.mlx_vlm_prompt,
        "maxTokens": settings.mlx_vlm_max_tokens,
        "chunkSeconds": settings.mlx_vlm_chunk_seconds,
        "overlapSeconds": settings.mlx_vlm_overlap_seconds,
        "overlapDedupeStrategy": "common-prefix-suffix-boundary",
    }

    def transcribe_chunk(chunk_path: Path) -> str:
        return clean_transcript_text(
            _run_mlx_vlm_generate(
                audio_path=chunk_path,
                model_path_or_repo=model_path_or_repo,
                prompt=settings.mlx_vlm_prompt,
                python_executable=status.python_executable,
                is_canceled=is_canceled,
            )
        )

    model_label = f"{Path(model_path_or_repo).name or model_path_or_repo}（MLX VLM Audio）"
    segments, partial = transcribe_audio_in_chunks(
        audio_path=audio_path,
        work_dir=active_work_dir,
        config=ChunkTranscriptionConfig(
            namespace="mlx_vlm_audio",
            engine_name="mlx-vlm-audio",
            model_label=model_label,
            chunk_seconds=float(settings.mlx_vlm_chunk_seconds),
            overlap_seconds=float(settings.mlx_vlm_overlap_seconds),
            metadata=base_metadata,
        ),
        transcribe_chunk=transcribe_chunk,
        is_canceled=is_canceled,
        on_partial=on_partial,
    )
    duration = audio_duration_seconds(audio_path)
    metadata = {
        **base_metadata,
        "partial_results": partial,
        "finalJson": {
            "segments": partial,
            "full_text": segment_text(segments, include_timestamps=False),
        },
        "duration": round(duration, 3),
    }
    return AudioEngineResult.from_segments(
        segments=segments,
        engine_name="mlx-vlm-audio",
        model_label=model_label,
        metadata=metadata,
    )
